name: Deploy Bot

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: echo "token=${{ secrets.GITHUB_TOKEN }}" >> .env

      - name: Install dependencies
        run: npm install

      - name: Run bot
        run: node src/index.js